# frozen_string_literal: true

# This file is autogenerated by Deimos, Do NOT modify
module Schemas; module MyNamespace
  ### Primary Schema Class ###
  # Autogenerated Schema for Record at com.my-namespace.MySchemaWithBooleans
  class MySchemaWithBoolean < Deimos::SchemaClass::Record

    ### Attribute Accessors ###
    # @return [String]
    attr_accessor :test_id
    # @return [Boolean]
    attr_accessor :some_bool

    # @override
    def initialize(_from_message: false, test_id: nil,
                   some_bool: nil)
      @_from_message = _from_message
      super
      self.test_id = test_id
      self.some_bool = some_bool
    end

    # @override
    def schema
      'MySchemaWithBooleans'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def as_json(_opts={})
      {
        'test_id' => @test_id,
        'some_bool' => @some_bool
      }
    end
  end
end; end
