# frozen_string_literal: true

# This file is autogenerated by Deimos, Do NOT modify
module Schemas; module MyNamespace
  ### Primary Schema Class ###
  # Autogenerated Schema for Record at com.my-namespace.WidgetTheThird
  class WidgetTheThird < Deimos::SchemaClass::Record

    ### Attribute Accessors ###
    # @return [String]
    attr_accessor :id
    # @return [Integer]
    attr_accessor :widget_id
    # @return [String]
    attr_accessor :model_id
    # @return [Integer]
    attr_accessor :updated_at
    # @return [Integer]
    attr_accessor :created_at

    # @override
    def initialize(_from_message: false, id: nil,
                   widget_id: nil,
                   model_id: nil,
                   updated_at: nil,
                   created_at: nil)
      @_from_message = _from_message
      super
      self.id = id
      self.widget_id = widget_id
      self.model_id = model_id
      self.updated_at = updated_at
      self.created_at = created_at
    end

    # @override
    def schema
      'WidgetTheThird'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def as_json(_opts={})
      {
        'id' => @id,
        'widget_id' => @widget_id,
        'model_id' => @model_id,
        'updated_at' => @updated_at,
        'created_at' => @created_at
      }
    end
  end
end; end
