# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activejob` gem.
# Please instead update this file by running `bin/tapioca gem activejob`.

# source://activejob//lib/active_job/gem_version.rb#3
module ActiveJob
  extend ::ActiveSupport::Autoload

  class << self
    # source://activejob//lib/active_job/gem_version.rb#5
    def gem_version; end

    # source://activejob//lib/active_job/version.rb#7
    def version; end
  end
end

# source://activejob//lib/active_job/arguments.rb#27
module ActiveJob::Arguments
  extend ::ActiveJob::Arguments

  # source://activejob//lib/active_job/arguments.rb#41
  def deserialize(arguments); end

  # source://activejob//lib/active_job/arguments.rb#33
  def serialize(arguments); end

  private

  # source://activejob//lib/active_job/arguments.rb#208
  def convert_to_global_id_hash(argument); end

  # source://activejob//lib/active_job/arguments.rb#155
  def custom_serialized?(hash); end

  # source://activejob//lib/active_job/arguments.rb#126
  def deserialize_argument(argument); end

  # source://activejob//lib/active_job/arguments.rb#151
  def deserialize_global_id(hash); end

  # source://activejob//lib/active_job/arguments.rb#165
  def deserialize_hash(serialized_hash); end

  # source://activejob//lib/active_job/arguments.rb#99
  def serialize_argument(argument); end

  # source://activejob//lib/active_job/arguments.rb#159
  def serialize_hash(argument); end

  # source://activejob//lib/active_job/arguments.rb#178
  def serialize_hash_key(key); end

  # source://activejob//lib/active_job/arguments.rb#189
  def serialize_indifferent_hash(indifferent_hash); end

  # source://activejob//lib/active_job/arguments.rb#147
  def serialized_global_id?(hash); end

  # source://activejob//lib/active_job/arguments.rb#195
  def transform_symbol_keys(hash, symbol_keys); end
end

# source://activejob//lib/active_job/arguments.rb#51
ActiveJob::Arguments::GLOBALID_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#59
ActiveJob::Arguments::OBJECT_SERIALIZER_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#49
ActiveJob::Arguments::PERMITTED_TYPES = T.let(T.unsafe(nil), Array)

# source://activejob//lib/active_job/arguments.rb#62
ActiveJob::Arguments::RESERVED_KEYS = T.let(T.unsafe(nil), Array)

# source://activejob//lib/active_job/arguments.rb#55
ActiveJob::Arguments::RUBY2_KEYWORDS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#53
ActiveJob::Arguments::SYMBOL_KEYS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#57
ActiveJob::Arguments::WITH_INDIFFERENT_ACCESS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/base.rb#63
class ActiveJob::Base
  include ::ActiveJob::Core
  include ::ActiveJob::QueueAdapter
  include ::ActiveJob::QueueName
  include ::ActiveJob::QueuePriority
  include ::ActiveJob::Enqueuing
  include ::ActiveSupport::Rescuable
  include ::ActiveJob::Execution
  include ::ActiveSupport::Callbacks
  include ::ActiveJob::Callbacks
  include ::ActiveJob::Exceptions
  include ::ActiveJob::Logging
  include ::ActiveJob::Instrumentation
  include ::ActiveJob::Timezones
  include ::ActiveJob::Translation
  include ::ActiveJob::TestHelper::TestQueueAdapter
  extend ::ActiveJob::Core::ClassMethods
  extend ::ActiveJob::QueueAdapter::ClassMethods
  extend ::ActiveJob::QueueName::ClassMethods
  extend ::ActiveJob::QueuePriority::ClassMethods
  extend ::ActiveJob::Enqueuing::ClassMethods
  extend ::ActiveSupport::Rescuable::ClassMethods
  extend ::ActiveJob::Execution::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveJob::Callbacks::ClassMethods
  extend ::ActiveJob::Exceptions::ClassMethods
  extend ::ActiveJob::TestHelper::TestQueueAdapter::ClassMethods

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
  def __callbacks; end

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
  def __callbacks?; end

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#835
  def _enqueue_callbacks; end

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#835
  def _perform_callbacks; end

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#823
  def _run_enqueue_callbacks(&block); end

  # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#823
  def _run_perform_callbacks(&block); end

  # source://activejob//lib/active_job/logging.rb#11
  def logger; end

  # source://activejob//lib/active_job/logging.rb#11
  def logger=(val); end

  # source://activejob//lib/active_job/queue_adapter.rb#15
  def queue_adapter(*_arg0, &_arg1); end

  # source://activejob//lib/active_job/queue_name.rb#58
  def queue_name_prefix; end

  # source://activejob//lib/active_job/queue_name.rb#58
  def queue_name_prefix=(_arg0); end

  # source://activejob//lib/active_job/queue_name.rb#58
  def queue_name_prefix?; end

  # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
  def rescue_handlers; end

  # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
  def rescue_handlers=(_arg0); end

  # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
  def rescue_handlers?; end

  class << self
    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks=(value); end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks?; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#827
    def _enqueue_callbacks; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#831
    def _enqueue_callbacks=(value); end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#827
    def _perform_callbacks; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#831
    def _perform_callbacks=(value); end

    # source://activejob//lib/active_job/queue_adapter.rb#13
    def _queue_adapter; end

    # source://activejob//lib/active_job/queue_adapter.rb#13
    def _queue_adapter=(value); end

    # source://activejob//lib/active_job/queue_adapter.rb#12
    def _queue_adapter_name; end

    # source://activejob//lib/active_job/queue_adapter.rb#12
    def _queue_adapter_name=(value); end

    # source://activejob//lib/active_job/test_helper.rb#19
    def _test_adapter; end

    # source://activejob//lib/active_job/test_helper.rb#19
    def _test_adapter=(value); end

    # source://activejob//lib/active_job/logging.rb#12
    def log_arguments; end

    # source://activejob//lib/active_job/logging.rb#12
    def log_arguments=(value); end

    # source://activejob//lib/active_job/logging.rb#12
    def log_arguments?; end

    # source://activejob//lib/active_job/logging.rb#11
    def logger; end

    # source://activejob//lib/active_job/logging.rb#11
    def logger=(val); end

    # source://activejob//lib/active_job/queue_priority.rb#32
    def priority; end

    # source://activejob//lib/active_job/queue_priority.rb#32
    def priority=(value); end

    # source://activejob//lib/active_job/queue_priority.rb#32
    def priority?; end

    # source://activejob//lib/active_job/queue_name.rb#56
    def queue_name; end

    # source://activejob//lib/active_job/queue_name.rb#56
    def queue_name=(value); end

    # source://activejob//lib/active_job/queue_name.rb#56
    def queue_name?; end

    # source://activejob//lib/active_job/queue_name.rb#57
    def queue_name_delimiter; end

    # source://activejob//lib/active_job/queue_name.rb#57
    def queue_name_delimiter=(value); end

    # source://activejob//lib/active_job/queue_name.rb#57
    def queue_name_delimiter?; end

    # source://activejob//lib/active_job/queue_name.rb#58
    def queue_name_prefix; end

    # source://activejob//lib/active_job/queue_name.rb#58
    def queue_name_prefix=(value); end

    # source://activejob//lib/active_job/queue_name.rb#58
    def queue_name_prefix?; end

    # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
    def rescue_handlers; end

    # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
    def rescue_handlers=(value); end

    # source://activesupport/6.1.7.3/lib/active_support/rescuable.rb#13
    def rescue_handlers?; end

    # source://activejob//lib/active_job/exceptions.rb#11
    def retry_jitter; end

    # source://activejob//lib/active_job/exceptions.rb#11
    def retry_jitter=(value); end

    # source://activesupport/6.1.7.3/lib/active_support/deprecation/method_wrappers.rb#63
    def return_false_on_aborted_enqueue(*args, &block); end

    # source://activesupport/6.1.7.3/lib/active_support/deprecation/method_wrappers.rb#63
    def return_false_on_aborted_enqueue=(*args, &block); end

    # source://activejob//lib/active_job/callbacks.rb#34
    def skip_after_callbacks_if_terminated; end

    # source://activejob//lib/active_job/callbacks.rb#34
    def skip_after_callbacks_if_terminated=(val); end
  end
end

# source://activejob//lib/active_job/callbacks.rb#22
module ActiveJob::Callbacks
  extend ::ActiveSupport::Concern
  extend ::ActiveSupport::Callbacks
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker
  mixes_in_class_methods ::ActiveJob::Callbacks::ClassMethods

  private

  # source://activejob//lib/active_job/callbacks.rb#183
  def halted_callback_hook(_filter, name); end

  class << self
    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks?; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#835
    def _execute_callbacks; end

    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#823
    def _run_execute_callbacks(&block); end
  end

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def __callbacks?; end
    def return_false_on_aborted_enqueue; end
    def return_false_on_aborted_enqueue=(value); end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def __callbacks?; end
  end
end

# source://activejob//lib/active_job/callbacks.rb#44
module ActiveJob::Callbacks::ClassMethods
  # source://activejob//lib/active_job/callbacks.rb#156
  def after_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#85
  def after_perform(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#177
  def around_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#118
  def around_perform(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#137
  def before_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#66
  def before_perform(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#45
  def inherited(klass); end
end

# source://activejob//lib/active_job/configured_job.rb#4
class ActiveJob::ConfiguredJob
  # source://activejob//lib/active_job/configured_job.rb#5
  def initialize(job_class, options = T.unsafe(nil)); end

  # source://activejob//lib/active_job/configured_job.rb#15
  def perform_later(*args); end

  # source://activejob//lib/active_job/configured_job.rb#10
  def perform_now(*args); end
end

# source://activejob//lib/active_job/core.rb#6
module ActiveJob::Core
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveJob::Core::ClassMethods

  # source://activejob//lib/active_job/core.rb#81
  def initialize(*arguments); end

  # source://activejob//lib/active_job/core.rb#10
  def arguments; end

  # source://activejob//lib/active_job/core.rb#10
  def arguments=(_arg0); end

  # source://activejob//lib/active_job/core.rb#136
  def deserialize(job_data); end

  # source://activejob//lib/active_job/core.rb#44
  def enqueued_at; end

  # source://activejob//lib/active_job/core.rb#44
  def enqueued_at=(_arg0); end

  # source://activejob//lib/active_job/core.rb#35
  def exception_executions; end

  # source://activejob//lib/active_job/core.rb#35
  def exception_executions=(_arg0); end

  # source://activejob//lib/active_job/core.rb#29
  def executions; end

  # source://activejob//lib/active_job/core.rb#29
  def executions=(_arg0); end

  # source://activejob//lib/active_job/core.rb#17
  def job_id; end

  # source://activejob//lib/active_job/core.rb#17
  def job_id=(_arg0); end

  # source://activejob//lib/active_job/core.rb#38
  def locale; end

  # source://activejob//lib/active_job/core.rb#38
  def locale=(_arg0); end

  # source://activejob//lib/active_job/core.rb#23
  def priority=(_arg0); end

  # source://activejob//lib/active_job/core.rb#26
  def provider_job_id; end

  # source://activejob//lib/active_job/core.rb#26
  def provider_job_id=(_arg0); end

  # source://activejob//lib/active_job/core.rb#20
  def queue_name=(_arg0); end

  # source://activejob//lib/active_job/core.rb#14
  def scheduled_at; end

  # source://activejob//lib/active_job/core.rb#14
  def scheduled_at=(_arg0); end

  # source://activejob//lib/active_job/core.rb#94
  def serialize; end

  # source://activejob//lib/active_job/core.rb#11
  def serialized_arguments=(_arg0); end

  # source://activejob//lib/active_job/core.rb#41
  def timezone; end

  # source://activejob//lib/active_job/core.rb#41
  def timezone=(_arg0); end

  private

  # source://activejob//lib/active_job/core.rb#173
  def arguments_serialized?; end

  # source://activejob//lib/active_job/core.rb#169
  def deserialize_arguments(serialized_args); end

  # source://activejob//lib/active_job/core.rb#158
  def deserialize_arguments_if_needed; end

  # source://activejob//lib/active_job/core.rb#165
  def serialize_arguments(arguments); end

  # source://activejob//lib/active_job/core.rb#150
  def serialize_arguments_if_needed(arguments); end
end

# source://activejob//lib/active_job/core.rb#48
module ActiveJob::Core::ClassMethods
  # source://activejob//lib/active_job/core.rb#50
  def deserialize(job_data); end

  # source://activejob//lib/active_job/core.rb#74
  def set(options = T.unsafe(nil)); end
end

# source://activejob//lib/active_job/arguments.rb#9
class ActiveJob::DeserializationError < ::StandardError
  # source://activejob//lib/active_job/arguments.rb#10
  def initialize; end
end

# source://activejob//lib/active_job/enqueuing.rb#7
module ActiveJob::Enqueuing
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveJob::Enqueuing::ClassMethods

  # source://activejob//lib/active_job/enqueuing.rb#48
  def enqueue(options = T.unsafe(nil)); end
end

# source://activejob//lib/active_job/enqueuing.rb#11
module ActiveJob::Enqueuing::ClassMethods
  # source://activejob//lib/active_job/enqueuing.rb#21
  def perform_later(*args); end

  private

  # source://activejob//lib/active_job/enqueuing.rb#27
  def job_or_instantiate(*args); end
end

# source://activejob//lib/active_job/exceptions.rb#7
module ActiveJob::Exceptions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::Exceptions::ClassMethods

  # source://activejob//lib/active_job/exceptions.rb#122
  def retry_job(options = T.unsafe(nil)); end

  private

  # source://activejob//lib/active_job/exceptions.rb#132
  def determine_delay(seconds_or_duration_or_algorithm:, executions:, jitter: T.unsafe(nil)); end

  # source://activejob//lib/active_job/exceptions.rb#152
  def determine_jitter_for_delay(delay, jitter); end

  # source://activejob//lib/active_job/exceptions.rb#157
  def executions_for(exceptions); end

  module GeneratedClassMethods
    def retry_jitter; end
    def retry_jitter=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/exceptions.rb#14
module ActiveJob::Exceptions::ClassMethods
  # source://activejob//lib/active_job/exceptions.rb#92
  def discard_on(*exceptions); end

  # source://activejob//lib/active_job/exceptions.rb#56
  def retry_on(*exceptions, wait: T.unsafe(nil), attempts: T.unsafe(nil), queue: T.unsafe(nil), priority: T.unsafe(nil), jitter: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/exceptions.rb#129
ActiveJob::Exceptions::JITTER_DEFAULT = T.let(T.unsafe(nil), Object)

# source://activejob//lib/active_job/execution.rb#7
module ActiveJob::Execution
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Rescuable

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Rescuable::ClassMethods
  mixes_in_class_methods ::ActiveJob::Execution::ClassMethods

  # source://activejob//lib/active_job/execution.rb#54
  def perform(*_arg0); end

  # source://activejob//lib/active_job/execution.rb#41
  def perform_now; end

  module GeneratedClassMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end

  module GeneratedInstanceMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end
end

# source://activejob//lib/active_job/execution.rb#12
module ActiveJob::Execution::ClassMethods
  # source://activejob//lib/active_job/execution.rb#22
  def execute(job_data); end

  # source://activejob//lib/active_job/execution.rb#17
  def perform_now(*args); end
end

# source://activejob//lib/active_job/instrumentation.rb#4
module ActiveJob::Instrumentation
  extend ::ActiveSupport::Concern

  private

  # source://activejob//lib/active_job/instrumentation.rb#35
  def halted_callback_hook(*_arg0); end

  # source://activejob//lib/active_job/instrumentation.rb#19
  def instrument(operation, payload = T.unsafe(nil), &block); end
end

# source://activejob//lib/active_job/log_subscriber.rb#7
class ActiveJob::LogSubscriber < ::ActiveSupport::LogSubscriber
  # source://activejob//lib/active_job/log_subscriber.rb#94
  def discard(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#8
  def enqueue(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#27
  def enqueue_at(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#71
  def enqueue_retry(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#53
  def perform(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#46
  def perform_start(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#85
  def retry_stopped(event); end

  private

  # source://activejob//lib/active_job/log_subscriber.rb#108
  def args_info(job); end

  # source://activejob//lib/active_job/log_subscriber.rb#117
  def format(arg); end

  # source://activejob//lib/active_job/log_subscriber.rb#134
  def logger; end

  # source://activejob//lib/active_job/log_subscriber.rb#104
  def queue_name(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#130
  def scheduled_at(event); end
end

# source://activejob//lib/active_job/logging.rb#7
module ActiveJob::Logging
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  private

  # source://activejob//lib/active_job/logging.rb#28
  def logger_tagged_by_active_job?; end

  # source://activejob//lib/active_job/logging.rb#19
  def tag_logger(*tags); end

  module GeneratedClassMethods
    def log_arguments; end
    def log_arguments=(value); end
    def log_arguments?; end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_adapter.rb#8
module ActiveJob::QueueAdapter
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueueAdapter::ClassMethods

  module GeneratedClassMethods
    def _queue_adapter; end
    def _queue_adapter=(value); end
    def _queue_adapter_name; end
    def _queue_adapter_name=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_adapter.rb#21
module ActiveJob::QueueAdapter::ClassMethods
  # source://activejob//lib/active_job/queue_adapter.rb#24
  def queue_adapter; end

  # source://activejob//lib/active_job/queue_adapter.rb#37
  def queue_adapter=(name_or_adapter); end

  # source://activejob//lib/active_job/queue_adapter.rb#30
  def queue_adapter_name; end

  private

  # source://activejob//lib/active_job/queue_adapter.rb#53
  def assign_adapter(adapter_name, queue_adapter); end

  # source://activejob//lib/active_job/queue_adapter.rb#60
  def queue_adapter?(object); end
end

# source://activejob//lib/active_job/queue_adapter.rb#58
ActiveJob::QueueAdapter::ClassMethods::QUEUE_ADAPTER_METHODS = T.let(T.unsafe(nil), Array)

# source://activejob//lib/active_job/queue_adapters.rb#113
module ActiveJob::QueueAdapters
  extend ::ActiveSupport::Autoload

  class << self
    # source://activejob//lib/active_job/queue_adapters.rb#136
    def lookup(name); end
  end
end

# source://activejob//lib/active_job/queue_adapters.rb#128
ActiveJob::QueueAdapters::ADAPTER = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#33
class ActiveJob::QueueAdapters::AsyncAdapter
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#35
  def initialize(**executor_options); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#39
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#43
  def enqueue_at(job, timestamp); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#55
  def immediate=(immediate); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#50
  def shutdown(wait: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#63
class ActiveJob::QueueAdapters::AsyncAdapter::JobWrapper
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#64
  def initialize(job); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#69
  def perform; end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#74
class ActiveJob::QueueAdapters::AsyncAdapter::Scheduler
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#86
  def initialize(**options); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#92
  def enqueue(job, queue_name:); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#96
  def enqueue_at(job, timestamp, queue_name:); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#110
  def executor; end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#84
  def immediate; end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#84
  def immediate=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#105
  def shutdown(wait: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#75
ActiveJob::QueueAdapters::AsyncAdapter::Scheduler::DEFAULT_EXECUTOR_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#13
class ActiveJob::QueueAdapters::InlineAdapter
  # source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#14
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#18
  def enqueue_at(*_arg0); end
end

# source://activejob//lib/active_job/queue_adapters/test_adapter.rb#14
class ActiveJob::QueueAdapters::TestAdapter
  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def at; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def at=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#28
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#33
  def enqueue_at(job, timestamp); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#19
  def enqueued_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#16
  def enqueued_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def filter; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def filter=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_at_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_at_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#24
  def performed_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#16
  def performed_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def queue; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def queue=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def reject; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def reject=(_arg0); end

  private

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#78
  def filter_as_proc(filter); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#56
  def filtered?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#70
  def filtered_job_class?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#64
  def filtered_queue?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#60
  def filtered_time?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#39
  def job_to_hash(job, extras = T.unsafe(nil)); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#47
  def perform_or_enqueue(perform, job, job_data); end
end

# source://activejob//lib/active_job/queue_name.rb#4
module ActiveJob::QueueName
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueueName::ClassMethods

  # source://activejob//lib/active_job/queue_name.rb#62
  def queue_name; end

  module GeneratedClassMethods
    def queue_name; end
    def queue_name=(value); end
    def queue_name?; end
    def queue_name_delimiter; end
    def queue_name_delimiter=(value); end
    def queue_name_delimiter?; end
    def queue_name_prefix; end
    def queue_name_prefix=(value); end
    def queue_name_prefix?; end
  end

  module GeneratedInstanceMethods
    def queue_name_prefix; end
    def queue_name_prefix=(value); end
    def queue_name_prefix?; end
  end
end

# source://activejob//lib/active_job/queue_name.rb#8
module ActiveJob::QueueName::ClassMethods
  # source://activejob//lib/active_job/queue_name.rb#9
  def default_queue_name; end

  # source://activejob//lib/active_job/queue_name.rb#9
  def default_queue_name=(val); end

  # source://activejob//lib/active_job/queue_name.rb#40
  def queue_as(part_name = T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/queue_name.rb#48
  def queue_name_from_part(part_name); end

  class << self
    # source://activejob//lib/active_job/queue_name.rb#9
    def default_queue_name; end

    # source://activejob//lib/active_job/queue_name.rb#9
    def default_queue_name=(val); end
  end
end

# source://activejob//lib/active_job/queue_priority.rb#4
module ActiveJob::QueuePriority
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueuePriority::ClassMethods

  # source://activejob//lib/active_job/queue_priority.rb#36
  def priority; end

  module GeneratedClassMethods
    def priority; end
    def priority=(value); end
    def priority?; end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_priority.rb#8
module ActiveJob::QueuePriority::ClassMethods
  # source://activejob//lib/active_job/queue_priority.rb#9
  def default_priority; end

  # source://activejob//lib/active_job/queue_priority.rb#9
  def default_priority=(val); end

  # source://activejob//lib/active_job/queue_priority.rb#22
  def queue_with_priority(priority = T.unsafe(nil), &block); end

  class << self
    # source://activejob//lib/active_job/queue_priority.rb#9
    def default_priority; end

    # source://activejob//lib/active_job/queue_priority.rb#9
    def default_priority=(val); end
  end
end

# source://activejob//lib/active_job/arguments.rb#25
class ActiveJob::SerializationError < ::ArgumentError; end

# source://activejob//lib/active_job/serializers.rb#8
module ActiveJob::Serializers
  extend ::ActiveSupport::Autoload

  # source://activejob//lib/active_job/serializers.rb#21
  def _additional_serializers; end

  # source://activejob//lib/active_job/serializers.rb#21
  def _additional_serializers=(val); end

  class << self
    # source://activejob//lib/active_job/serializers.rb#21
    def _additional_serializers; end

    # source://activejob//lib/active_job/serializers.rb#21
    def _additional_serializers=(val); end

    # source://activejob//lib/active_job/serializers.rb#53
    def add_serializers(*new_serializers); end

    # source://activejob//lib/active_job/serializers.rb#37
    def deserialize(argument); end

    # source://activejob//lib/active_job/serializers.rb#28
    def serialize(argument); end

    # source://activejob//lib/active_job/serializers.rb#48
    def serializers; end
  end
end

# source://activejob//lib/active_job/serializers/date_serializer.rb#5
class ActiveJob::Serializers::DateSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/date_serializer.rb#10
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/date_serializer.rb#6
  def serialize(date); end

  private

  # source://activejob//lib/active_job/serializers/date_serializer.rb#15
  def klass; end
end

# source://activejob//lib/active_job/serializers/date_time_serializer.rb#5
class ActiveJob::Serializers::DateTimeSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  # source://activejob//lib/active_job/serializers/date_time_serializer.rb#6
  def deserialize(hash); end

  private

  # source://activejob//lib/active_job/serializers/date_time_serializer.rb#11
  def klass; end
end

# source://activejob//lib/active_job/serializers/duration_serializer.rb#5
class ActiveJob::Serializers::DurationSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/duration_serializer.rb#10
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/duration_serializer.rb#6
  def serialize(duration); end

  private

  # source://activejob//lib/active_job/serializers/duration_serializer.rb#18
  def klass; end
end

# source://activejob//lib/active_job/serializers/module_serializer.rb#5
class ActiveJob::Serializers::ModuleSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/module_serializer.rb#10
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/module_serializer.rb#6
  def serialize(constant); end

  private

  # source://activejob//lib/active_job/serializers/module_serializer.rb#15
  def klass; end
end

# source://activejob//lib/active_job/serializers/object_serializer.rb#24
class ActiveJob::Serializers::ObjectSerializer
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # source://activejob//lib/active_job/serializers/object_serializer.rb#42
  def deserialize(json); end

  # source://activejob//lib/active_job/serializers/object_serializer.rb#37
  def serialize(hash); end

  # source://activejob//lib/active_job/serializers/object_serializer.rb#32
  def serialize?(argument); end

  private

  # source://activejob//lib/active_job/serializers/object_serializer.rb#48
  def klass; end

  class << self
    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def deserialize(*_arg0, &_arg1); end

    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def serialize(*_arg0, &_arg1); end

    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def serialize?(*_arg0, &_arg1); end
  end
end

# source://activejob//lib/active_job/serializers/symbol_serializer.rb#5
class ActiveJob::Serializers::SymbolSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#10
  def deserialize(argument); end

  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#6
  def serialize(argument); end

  private

  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#15
  def klass; end
end

# source://activejob//lib/active_job/serializers/time_object_serializer.rb#5
class ActiveJob::Serializers::TimeObjectSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/time_object_serializer.rb#8
  def serialize(time); end
end

# source://activejob//lib/active_job/serializers/time_object_serializer.rb#6
ActiveJob::Serializers::TimeObjectSerializer::NANO_PRECISION = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/serializers/time_serializer.rb#5
class ActiveJob::Serializers::TimeSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  # source://activejob//lib/active_job/serializers/time_serializer.rb#6
  def deserialize(hash); end

  private

  # source://activejob//lib/active_job/serializers/time_serializer.rb#11
  def klass; end
end

# source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#5
class ActiveJob::Serializers::TimeWithZoneSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  # source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#6
  def deserialize(hash); end

  private

  # source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#11
  def klass; end
end

# source://activejob//lib/active_job/test_case.rb#6
class ActiveJob::TestCase < ::ActiveSupport::TestCase
  include ::ActiveJob::TestHelper
end

# source://activejob//lib/active_job/test_helper.rb#8
module ActiveJob::TestHelper
  include ::ActiveSupport::Testing::Assertions

  # source://activejob//lib/active_job/test_helper.rb#51
  def after_teardown; end

  # source://activejob//lib/active_job/test_helper.rb#123
  def assert_enqueued_jobs(number, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#392
  def assert_enqueued_with(job: T.unsafe(nil), args: T.unsafe(nil), at: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#185
  def assert_no_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#343
  def assert_no_performed_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#275
  def assert_performed_jobs(number, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#482
  def assert_performed_with(job: T.unsafe(nil), args: T.unsafe(nil), at: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#39
  def before_setup; end

  # source://activejob//lib/active_job/test_helper.rb#9
  def enqueued_jobs(*_arg0, &_arg1); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def enqueued_jobs=(arg); end

  # source://activejob//lib/active_job/test_helper.rb#574
  def perform_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def performed_jobs(*_arg0, &_arg1); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def performed_jobs=(arg); end

  # source://activejob//lib/active_job/test_helper.rb#610
  def queue_adapter; end

  # source://activejob//lib/active_job/test_helper.rb#66
  def queue_adapter_for_test; end

  private

  # source://activejob//lib/active_job/test_helper.rb#615
  def clear_enqueued_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#619
  def clear_performed_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#680
  def deserialize_args_for_assertion(job); end

  # source://activejob//lib/active_job/test_helper.rb#655
  def enqueued_jobs_with(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#649
  def filter_as_proc(filter); end

  # source://activejob//lib/active_job/test_helper.rb#663
  def flush_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil)); end

  # source://activejob//lib/active_job/test_helper.rb#687
  def instantiate_job(payload); end

  # source://activejob//lib/active_job/test_helper.rb#623
  def jobs_with(jobs, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil)); end

  # source://activejob//lib/active_job/test_helper.rb#659
  def performed_jobs_with(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#671
  def prepare_args_for_assertion(args); end

  # source://activejob//lib/active_job/test_helper.rb#694
  def queue_adapter_changed_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#701
  def validate_option(only: T.unsafe(nil), except: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/test_helper.rb#15
module ActiveJob::TestHelper::TestQueueAdapter
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::TestHelper::TestQueueAdapter::ClassMethods

  module GeneratedClassMethods
    def _test_adapter; end
    def _test_adapter=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/test_helper.rb#22
module ActiveJob::TestHelper::TestQueueAdapter::ClassMethods
  # source://activejob//lib/active_job/test_helper.rb#27
  def disable_test_adapter; end

  # source://activejob//lib/active_job/test_helper.rb#31
  def enable_test_adapter(test_adapter); end

  # source://activejob//lib/active_job/test_helper.rb#23
  def queue_adapter; end
end

# source://activejob//lib/active_job/timezones.rb#4
module ActiveJob::Timezones
  extend ::ActiveSupport::Concern
end

# source://activejob//lib/active_job/translation.rb#4
module ActiveJob::Translation
  extend ::ActiveSupport::Concern
end

# source://activejob//lib/active_job/gem_version.rb#9
module ActiveJob::VERSION; end

# source://activejob//lib/active_job/gem_version.rb#10
ActiveJob::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/gem_version.rb#11
ActiveJob::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/gem_version.rb#13
ActiveJob::VERSION::PRE = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/gem_version.rb#15
ActiveJob::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/gem_version.rb#12
ActiveJob::VERSION::TINY = T.let(T.unsafe(nil), Integer)
