# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-pop` gem.
# Please instead update this file by running `bin/tapioca gem net-pop`.

# source://net-pop//lib/net/pop.rb#730
class Net::APOP < ::Net::POP3
  # source://net-pop//lib/net/pop.rb#731
  def apop?; end
end

# source://net-pop//lib/net/pop.rb#737
Net::APOPSession = Net::APOP

# source://net-pop//lib/net/pop.rb#722
Net::POP = Net::POP3

# source://net-pop//lib/net/pop.rb#197
class Net::POP3 < ::Net::Protocol
  # source://net-pop//lib/net/pop.rb#417
  def initialize(addr, port = T.unsafe(nil), isapop = T.unsafe(nil)); end

  # source://net-pop//lib/net/pop.rb#514
  def active?; end

  # source://net-pop//lib/net/pop.rb#490
  def address; end

  # source://net-pop//lib/net/pop.rb#436
  def apop?; end

  # source://net-pop//lib/net/pop.rb#314
  def auth_only(account, password); end

  # source://net-pop//lib/net/pop.rb#690
  def delete_all; end

  # source://net-pop//lib/net/pop.rb#463
  def disable_ssl; end

  # source://net-pop//lib/net/pop.rb#668
  def each(&block); end

  # source://net-pop//lib/net/pop.rb#668
  def each_mail(&block); end

  # source://net-pop//lib/net/pop.rb#452
  def enable_ssl(verify_or_params = T.unsafe(nil), certs = T.unsafe(nil), port = T.unsafe(nil)); end

  # source://net-pop//lib/net/pop.rb#589
  def finish; end

  # source://net-pop//lib/net/pop.rb#468
  def inspect; end

  # source://net-pop//lib/net/pop.rb#715
  def logging(msg); end

  # source://net-pop//lib/net/pop.rb#646
  def mails; end

  # source://net-pop//lib/net/pop.rb#634
  def n_bytes; end

  # source://net-pop//lib/net/pop.rb#627
  def n_mails; end

  # source://net-pop//lib/net/pop.rb#500
  def open_timeout; end

  # source://net-pop//lib/net/pop.rb#500
  def open_timeout=(_arg0); end

  # source://net-pop//lib/net/pop.rb#493
  def port; end

  # source://net-pop//lib/net/pop.rb#505
  def read_timeout; end

  # source://net-pop//lib/net/pop.rb#508
  def read_timeout=(sec); end

  # source://net-pop//lib/net/pop.rb#700
  def reset; end

  # source://net-pop//lib/net/pop.rb#709
  def set_all_uids; end

  # source://net-pop//lib/net/pop.rb#485
  def set_debug_output(arg); end

  # source://net-pop//lib/net/pop.rb#526
  def start(account, password); end

  # source://net-pop//lib/net/pop.rb#514
  def started?; end

  # source://net-pop//lib/net/pop.rb#441
  def use_ssl?; end

  private

  # source://net-pop//lib/net/pop.rb#615
  def command; end

  # source://net-pop//lib/net/pop.rb#599
  def do_finish; end

  # source://net-pop//lib/net/pop.rb#542
  def do_start(account, password); end

  # source://net-pop//lib/net/pop.rb#584
  def on_connect; end

  class << self
    # source://net-pop//lib/net/pop.rb#238
    def APOP(isapop); end

    # source://net-pop//lib/net/pop.rb#305
    def auth_only(address, port = T.unsafe(nil), account = T.unsafe(nil), password = T.unsafe(nil), isapop = T.unsafe(nil)); end

    # source://net-pop//lib/net/pop.rb#377
    def certs; end

    # source://net-pop//lib/net/pop.rb#337
    def create_ssl_params(verify_or_params = T.unsafe(nil), certs = T.unsafe(nil)); end

    # source://net-pop//lib/net/pop.rb#210
    def default_pop3_port; end

    # source://net-pop//lib/net/pop.rb#215
    def default_pop3s_port; end

    # source://net-pop//lib/net/pop.rb#205
    def default_port; end

    # source://net-pop//lib/net/pop.rb#283
    def delete_all(address, port = T.unsafe(nil), account = T.unsafe(nil), password = T.unsafe(nil), isapop = T.unsafe(nil), &block); end

    # source://net-pop//lib/net/pop.rb#355
    def disable_ssl; end

    # source://net-pop//lib/net/pop.rb#332
    def enable_ssl(*args); end

    # source://net-pop//lib/net/pop.rb#262
    def foreach(address, port = T.unsafe(nil), account = T.unsafe(nil), password = T.unsafe(nil), isapop = T.unsafe(nil), &block); end

    # source://net-pop//lib/net/pop.rb#219
    def socket_type; end

    # source://net-pop//lib/net/pop.rb#362
    def ssl_params; end

    # source://net-pop//lib/net/pop.rb#401
    def start(address, port = T.unsafe(nil), account = T.unsafe(nil), password = T.unsafe(nil), isapop = T.unsafe(nil), &block); end

    # source://net-pop//lib/net/pop.rb#367
    def use_ssl?; end

    # source://net-pop//lib/net/pop.rb#372
    def verify; end
  end
end

# source://net-pop//lib/net/pop.rb#198
Net::POP3::VERSION = T.let(T.unsafe(nil), String)

# source://net-pop//lib/net/pop.rb#892
class Net::POP3Command
  # source://net-pop//lib/net/pop.rb#894
  def initialize(sock); end

  # source://net-pop//lib/net/pop.rb#914
  def apop(account, password); end

  # source://net-pop//lib/net/pop.rb#907
  def auth(account, password); end

  # source://net-pop//lib/net/pop.rb#962
  def dele(num); end

  # source://net-pop//lib/net/pop.rb#903
  def inspect; end

  # source://net-pop//lib/net/pop.rb#924
  def list; end

  # source://net-pop//lib/net/pop.rb#983
  def quit; end

  # source://net-pop//lib/net/pop.rb#955
  def retr(num, &block); end

  # source://net-pop//lib/net/pop.rb#944
  def rset; end

  # source://net-pop//lib/net/pop.rb#901
  def socket; end

  # source://net-pop//lib/net/pop.rb#937
  def stat; end

  # source://net-pop//lib/net/pop.rb#948
  def top(num, lines = T.unsafe(nil), &block); end

  # source://net-pop//lib/net/pop.rb#966
  def uidl(num = T.unsafe(nil)); end

  private

  # source://net-pop//lib/net/pop.rb#1003
  def check_response(res); end

  # source://net-pop//lib/net/pop.rb#1008
  def check_response_auth(res); end

  # source://net-pop//lib/net/pop.rb#1013
  def critical; end

  # source://net-pop//lib/net/pop.rb#994
  def get_response(fmt, *fargs); end

  # source://net-pop//lib/net/pop.rb#989
  def getok(fmt, *fargs); end

  # source://net-pop//lib/net/pop.rb#999
  def recv_response; end
end

# source://net-pop//lib/net/pop.rb#724
Net::POP3Session = Net::POP3

# source://net-pop//lib/net/pop.rb#40
class Net::POPAuthenticationError < ::Net::ProtoAuthError; end

# source://net-pop//lib/net/pop.rb#43
class Net::POPBadResponse < ::Net::POPError; end

# source://net-pop//lib/net/pop.rb#37
class Net::POPError < ::Net::ProtocolError; end

# source://net-pop//lib/net/pop.rb#744
class Net::POPMail
  # source://net-pop//lib/net/pop.rb#746
  def initialize(num, len, pop, cmd); end

  # source://net-pop//lib/net/pop.rb#805
  def all(dest = T.unsafe(nil), &block); end

  # source://net-pop//lib/net/pop.rb#861
  def delete; end

  # source://net-pop//lib/net/pop.rb#861
  def delete!; end

  # source://net-pop//lib/net/pop.rb#869
  def deleted?; end

  # source://net-pop//lib/net/pop.rb#837
  def header(dest = T.unsafe(nil)); end

  # source://net-pop//lib/net/pop.rb#763
  def inspect; end

  # source://net-pop//lib/net/pop.rb#759
  def length; end

  # source://net-pop//lib/net/pop.rb#805
  def mail(dest = T.unsafe(nil), &block); end

  # source://net-pop//lib/net/pop.rb#756
  def number; end

  # source://net-pop//lib/net/pop.rb#805
  def pop(dest = T.unsafe(nil), &block); end

  # source://net-pop//lib/net/pop.rb#759
  def size; end

  # source://net-pop//lib/net/pop.rb#825
  def top(lines, dest = T.unsafe(nil)); end

  # source://net-pop//lib/net/pop.rb#885
  def uid=(uid); end

  # source://net-pop//lib/net/pop.rb#877
  def uidl; end

  # source://net-pop//lib/net/pop.rb#877
  def unique_id; end
end

# source://net-pop//lib/net/pop.rb#723
Net::POPSession = Net::POP3
