# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-smtp` gem.
# Please instead update this file by running `bin/tapioca gem net-smtp`.

# source://net-smtp//lib/net/smtp.rb#188
class Net::SMTP < ::Net::Protocol
  # source://net-smtp//lib/net/smtp.rb#241
  def initialize(address, port = T.unsafe(nil), tls: T.unsafe(nil), starttls: T.unsafe(nil), tls_verify: T.unsafe(nil), tls_hostname: T.unsafe(nil), ssl_context_params: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#406
  def address; end

  # source://net-smtp//lib/net/smtp.rb#860
  def auth_cram_md5(user, secret); end

  # source://net-smtp//lib/net/smtp.rb#849
  def auth_login(user, secret); end

  # source://net-smtp//lib/net/smtp.rb#840
  def auth_plain(user, secret); end

  # source://net-smtp//lib/net/smtp.rb#834
  def authenticate(user, secret, authtype = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#300
  def capabilities; end

  # source://net-smtp//lib/net/smtp.rb#294
  def capable?(key); end

  # source://net-smtp//lib/net/smtp.rb#329
  def capable_auth_types; end

  # source://net-smtp//lib/net/smtp.rb#316
  def capable_cram_md5_auth?; end

  # source://net-smtp//lib/net/smtp.rb#310
  def capable_login_auth?; end

  # source://net-smtp//lib/net/smtp.rb#304
  def capable_plain_auth?; end

  # source://net-smtp//lib/net/smtp.rb#289
  def capable_starttls?; end

  # source://net-smtp//lib/net/smtp.rb#998
  def data(msgstr = T.unsafe(nil), &block); end

  # source://net-smtp//lib/net/smtp.rb#442
  def debug_output=(arg); end

  # source://net-smtp//lib/net/smtp.rb#356
  def disable_ssl; end

  # source://net-smtp//lib/net/smtp.rb#400
  def disable_starttls; end

  # source://net-smtp//lib/net/smtp.rb#356
  def disable_tls; end

  # source://net-smtp//lib/net/smtp.rb#938
  def ehlo(domain); end

  # source://net-smtp//lib/net/smtp.rb#345
  def enable_ssl(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#382
  def enable_starttls(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#391
  def enable_starttls_auto(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#345
  def enable_tls(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#282
  def esmtp; end

  # source://net-smtp//lib/net/smtp.rb#282
  def esmtp=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#282
  def esmtp?; end

  # source://net-smtp//lib/net/smtp.rb#624
  def finish; end

  # source://net-smtp//lib/net/smtp.rb#934
  def helo(domain); end

  # source://net-smtp//lib/net/smtp.rb#271
  def inspect; end

  # source://net-smtp//lib/net/smtp.rb#943
  def mailfrom(from_addr); end

  # source://net-smtp//lib/net/smtp.rb#818
  def open_message_stream(from_addr, *to_addrs, &block); end

  # source://net-smtp//lib/net/smtp.rb#414
  def open_timeout; end

  # source://net-smtp//lib/net/smtp.rb#414
  def open_timeout=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#409
  def port; end

  # source://net-smtp//lib/net/smtp.rb#1025
  def quit; end

  # source://net-smtp//lib/net/smtp.rb#970
  def rcptto(to_addr); end

  # source://net-smtp//lib/net/smtp.rb#948
  def rcptto_list(to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#419
  def read_timeout; end

  # source://net-smtp//lib/net/smtp.rb#423
  def read_timeout=(sec); end

  # source://net-smtp//lib/net/smtp.rb#818
  def ready(from_addr, *to_addrs, &block); end

  # source://net-smtp//lib/net/smtp.rb#926
  def rset; end

  # source://net-smtp//lib/net/smtp.rb#765
  def send_mail(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#765
  def send_message(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#765
  def sendmail(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#442
  def set_debug_output(arg); end

  # source://net-smtp//lib/net/smtp.rb#336
  def ssl?; end

  # source://net-smtp//lib/net/smtp.rb#268
  def ssl_context_params; end

  # source://net-smtp//lib/net/smtp.rb#268
  def ssl_context_params=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#591
  def start(*args, helo: T.unsafe(nil), user: T.unsafe(nil), secret: T.unsafe(nil), password: T.unsafe(nil), authtype: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#532
  def started?; end

  # source://net-smtp//lib/net/smtp.rb#930
  def starttls; end

  # source://net-smtp//lib/net/smtp.rb#366
  def starttls?; end

  # source://net-smtp//lib/net/smtp.rb#371
  def starttls_always?; end

  # source://net-smtp//lib/net/smtp.rb#376
  def starttls_auto?; end

  # source://net-smtp//lib/net/smtp.rb#336
  def tls?; end

  # source://net-smtp//lib/net/smtp.rb#265
  def tls_hostname; end

  # source://net-smtp//lib/net/smtp.rb#265
  def tls_hostname=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#262
  def tls_verify; end

  # source://net-smtp//lib/net/smtp.rb#262
  def tls_verify=(_arg0); end

  private

  # source://net-smtp//lib/net/smtp.rb#320
  def auth_capable?(type); end

  # source://net-smtp//lib/net/smtp.rb#880
  def auth_method(type); end

  # source://net-smtp//lib/net/smtp.rb#893
  def base64_encode(str); end

  # source://net-smtp//lib/net/smtp.rb#884
  def check_auth_args(user, secret, authtype = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#1092
  def check_auth_continue(res); end

  # source://net-smtp//lib/net/smtp.rb#874
  def check_auth_method(type); end

  # source://net-smtp//lib/net/smtp.rb#1086
  def check_auth_response(res); end

  # source://net-smtp//lib/net/smtp.rb#1080
  def check_continue(res); end

  # source://net-smtp//lib/net/smtp.rb#1074
  def check_response(res); end

  # source://net-smtp//lib/net/smtp.rb#902
  def cram_md5_response(secret, challenge); end

  # source://net-smtp//lib/net/smtp.rb#909
  def cram_secret(secret, mask); end

  # source://net-smtp//lib/net/smtp.rb#1064
  def critical; end

  # source://net-smtp//lib/net/smtp.rb#631
  def digest_class; end

  # source://net-smtp//lib/net/smtp.rb#714
  def do_finish; end

  # source://net-smtp//lib/net/smtp.rb#702
  def do_helo(helo_domain); end

  # source://net-smtp//lib/net/smtp.rb#650
  def do_start(helo_domain, user, secret, authtype); end

  # source://net-smtp//lib/net/smtp.rb#1048
  def get_response(reqline); end

  # source://net-smtp//lib/net/smtp.rb#1038
  def getok(reqline); end

  # source://net-smtp//lib/net/smtp.rb#1177
  def logging(msg); end

  # source://net-smtp//lib/net/smtp.rb#697
  def new_internet_message_io(s); end

  # source://net-smtp//lib/net/smtp.rb#1054
  def recv_response; end

  # source://net-smtp//lib/net/smtp.rb#680
  def ssl_socket(socket, context); end

  # source://net-smtp//lib/net/smtp.rb#641
  def tcp_socket(address, port); end

  # source://net-smtp//lib/net/smtp.rb#684
  def tlsconnect(s, context); end

  # source://net-smtp//lib/net/smtp.rb#1031
  def validate_line(line); end

  class << self
    # source://net-smtp//lib/net/smtp.rb#194
    def default_port; end

    # source://net-smtp//lib/net/smtp.rb#212
    def default_ssl_context(ssl_context_params = T.unsafe(nil)); end

    # source://net-smtp//lib/net/smtp.rb#204
    def default_ssl_port; end

    # source://net-smtp//lib/net/smtp.rb#199
    def default_submission_port; end

    # source://net-smtp//lib/net/smtp.rb#204
    def default_tls_port; end

    # source://net-smtp//lib/net/smtp.rb#518
    def start(address, port = T.unsafe(nil), *args, helo: T.unsafe(nil), user: T.unsafe(nil), secret: T.unsafe(nil), password: T.unsafe(nil), authtype: T.unsafe(nil), tls: T.unsafe(nil), starttls: T.unsafe(nil), tls_verify: T.unsafe(nil), tls_hostname: T.unsafe(nil), ssl_context_params: T.unsafe(nil), &block); end
  end
end

# source://net-smtp//lib/net/smtp.rb#1182
class Net::SMTP::Address
  # source://net-smtp//lib/net/smtp.rb#1193
  def initialize(address, *args, **kw_args); end

  # source://net-smtp//lib/net/smtp.rb#1184
  def address; end

  # source://net-smtp//lib/net/smtp.rb#1186
  def parameters; end

  # source://net-smtp//lib/net/smtp.rb#1203
  def to_s; end
end

# source://net-smtp//lib/net/smtp.rb#1102
class Net::SMTP::Response
  # source://net-smtp//lib/net/smtp.rb#1111
  def initialize(status, string); end

  # source://net-smtp//lib/net/smtp.rb#1154
  def capabilities; end

  # source://net-smtp//lib/net/smtp.rb#1135
  def continue?; end

  # source://net-smtp//lib/net/smtp.rb#1146
  def cram_md5_challenge; end

  # source://net-smtp//lib/net/smtp.rb#1166
  def exception_class; end

  # source://net-smtp//lib/net/smtp.rb#1140
  def message; end

  # source://net-smtp//lib/net/smtp.rb#1117
  def status; end

  # source://net-smtp//lib/net/smtp.rb#1123
  def status_type_char; end

  # source://net-smtp//lib/net/smtp.rb#1120
  def string; end

  # source://net-smtp//lib/net/smtp.rb#1129
  def success?; end

  class << self
    # source://net-smtp//lib/net/smtp.rb#1105
    def parse(str); end
  end
end

# source://net-smtp//lib/net/smtp.rb#189
Net::SMTP::VERSION = T.let(T.unsafe(nil), String)

# source://net-smtp//lib/net/smtp.rb#55
class Net::SMTPAuthenticationError < ::Net::ProtoAuthError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#33
module Net::SMTPError
  # source://net-smtp//lib/net/smtp.rb#39
  def initialize(response, message: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#49
  def message; end

  # source://net-smtp//lib/net/smtp.rb#37
  def response; end
end

# source://net-smtp//lib/net/smtp.rb#70
class Net::SMTPFatalError < ::Net::ProtoFatalError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#60
class Net::SMTPServerBusy < ::Net::ProtoServerError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#1210
Net::SMTPSession = Net::SMTP

# source://net-smtp//lib/net/smtp.rb#65
class Net::SMTPSyntaxError < ::Net::ProtoSyntaxError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#75
class Net::SMTPUnknownError < ::Net::ProtoUnknownError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#80
class Net::SMTPUnsupportedCommand < ::Net::ProtocolError
  include ::Net::SMTPError
end
