# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `unicode-display_width` gem.
# Please instead update this file by running `bin/tapioca gem unicode-display_width`.

# source://unicode-display_width//lib/unicode/display_width/no_string_ext.rb#1
module Unicode; end

# source://unicode-display_width//lib/unicode/display_width/no_string_ext.rb#2
module Unicode::DisplayWidth
  class << self
    # source://unicode-display_width//lib/unicode/display_width.rb#26
    def emoji_extra_width_of(string, ambiguous = T.unsafe(nil), overwrite = T.unsafe(nil), _ = T.unsafe(nil)); end

    # source://unicode-display_width//lib/unicode/display_width.rb#8
    def of(string, ambiguous = T.unsafe(nil), overwrite = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

# source://unicode-display_width//lib/unicode/display_width/constants.rb#5
Unicode::DisplayWidth::DATA_DIRECTORY = T.let(T.unsafe(nil), String)

# source://unicode-display_width//lib/unicode/display_width.rb#6
Unicode::DisplayWidth::DEPTHS = T.let(T.unsafe(nil), Array)

# source://unicode-display_width//lib/unicode/display_width/index.rb#9
Unicode::DisplayWidth::INDEX = T.let(T.unsafe(nil), Array)

# source://unicode-display_width//lib/unicode/display_width/constants.rb#6
Unicode::DisplayWidth::INDEX_FILENAME = T.let(T.unsafe(nil), String)

# source://unicode-display_width//lib/unicode/display_width/no_string_ext.rb#3
Unicode::DisplayWidth::NO_STRING_EXT = T.let(T.unsafe(nil), TrueClass)

# source://unicode-display_width//lib/unicode/display_width/constants.rb#4
Unicode::DisplayWidth::UNICODE_VERSION = T.let(T.unsafe(nil), String)

# source://unicode-display_width//lib/unicode/display_width/constants.rb#3
Unicode::DisplayWidth::VERSION = T.let(T.unsafe(nil), String)
