# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Parser::AST::Node; end
module Parser::Builders::Default; end
module Parser::Source::Comment; end
module Parser::Source::Map; end
module Parser::Source::TreeRewriter; end
module URI::Escape; end
