# frozen_string_literal: true

# This file is autogenerated by Deimos, Do NOT modify
module Deimos
  # :nodoc:
  class ARecord < SchemaClass::Record

    # @param value [String]
    attr_accessor :a_record_field
    # @return [Object] An optional payload key
    attr_accessor :payload_key

    # @override
    def initialize(a_record_field: nil,
                   payload_key: nil)
      super()
      self.a_record_field = a_record_field
      self.payload_key = payload_key
    end

    # @override
    def schema
      'ARecord'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      payload = {
        'a_record_field' => @a_record_field
      }
      @payload_key.present? ? payload.merge('payload_key' => @payload_key) : payload
    end
  end
end
