# frozen_string_literal: true

# autogenerated by Deimos, do not modify
module Deimos
  # :nodoc:
  class MyNestedSchema < SchemaRecord
    # @return [String]
    attr_accessor :test_id
    # @return [Float]
    attr_accessor :test_float
    # @return [Array<String>]
    attr_accessor :test_array
    # @return [Deimos::MyNestedRecord]
    attr_accessor :some_nested_record
    # @return [nil, Deimos::MyNestedRecord]
    attr_accessor :some_optional_record
    # @return [Object] An optional payload key
    attr_accessor :payload_key

    # @override
    def initialize(test_id:, test_float:, test_array:, some_nested_record:, some_optional_record:,
                   payload_key:nil)
      @test_id = test_id
      @test_float = test_float
      @test_array = test_array
      @some_nested_record = some_nested_record
      @some_optional_record = some_optional_record
      @payload_key = payload_key
    end

    # @override
    def self.initialize_from_payload(payload)
      return unless payload.present?

      args = {}
      payload.each do |key, value|
        args[key.to_sym] = case key.to_sym
                           when :some_nested_record, :some_optional_record
                             Deimos::MyNestedRecord.initialize_from_payload(value)
                           else
                             value
                           end
      end
      self.new(**args)
    end

    # @override
    def schema
      'MyNestedSchema'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      payload = {
        'test_id' => @test_id,
        'test_float' => @test_float,
        'test_array' => @test_array,
        'some_nested_record' => @some_nested_record&.to_h,
        'some_optional_record' => @some_optional_record&.to_h
      }
      @payload_key.present? ? payload.merge('payload_key' => @payload_key) : payload
    end
  end
end
