# frozen_string_literal: true

# autogenerated by Deimos, do not modify
module Deimos
  # :nodoc:
  class MySchemaWithComplexTypes < SchemaRecord
    ### Attribute Readers ###
    # @return [String]
    attr_reader :test_id
    # @return [Float]
    attr_reader :test_float
    # @return [Array<String>]
    attr_reader :test_array
    # @return [Deimos::ARecord]
    attr_reader :some_record
    # @return [nil, Deimos::ARecord]
    attr_reader :some_optional_record
    # @return [Array<Deimos::ARecord>]
    attr_reader :some_record_array
    # @return [Hash<String, Deimos::ARecord>]
    attr_reader :some_record_map
    # @return [Array<Deimos::AnEnum>]
    attr_reader :some_enum_array

    # @return [Object] An optional payload key
    attr_accessor :payload_key

    ### Attribute Setters ###
    # @param value [String]
    def test_id=(value)
      @test_id = value
    end

    # @param value [Float]
    def test_float=(value)
      @test_float = value
    end

    # @param values [Array<String>]
    def test_array=(values)
      @test_array = values.map do |value|
        value
      end
    end

    # @param value [Deimos::ARecord]
    def some_record=(value)
      @some_record = value.present? && !value.is_a?(Deimos::ARecord) ? Deimos::ARecord.new(**value) : value
    end

    # @param value [nil, Deimos::ARecord]
    def some_optional_record=(value)
      @some_optional_record = value.present? && !value.is_a?(Deimos::ARecord) ? Deimos::ARecord.new(**value) : value
    end

    # @param values [Array<Deimos::ARecord>]
    def some_record_array=(values)
      @some_record_array = values.map do |value|
        value.present? && !value.is_a?(Deimos::ARecord) ? Deimos::ARecord.new(**value) : value
      end
    end

    # @param values [Hash<String, Deimos::ARecord>]
    def some_record_map=(values)
      @some_record_map = values.transform_values do |value|
        value.present? && !value.is_a?(Deimos::ARecord) ? Deimos::ARecord.new(**value) : value
      end
    end

    # @param values [Array<Deimos::AnEnum>]
    def some_enum_array=(values)
      @some_enum_array = values.map do |value|
        value.present? && !value.is_a?(Deimos::AnEnum) ? Deimos::AnEnum.new(value) : value
      end
    end

    # @override
    def initialize(test_id:, test_float:, test_array:, some_record:, some_optional_record:,
                   some_record_array:, some_record_map:, some_enum_array:, payload_key: nil)
      super()
      self.test_id = test_id
      self.test_float = test_float
      self.test_array = test_array
      self.some_record = some_record
      self.some_optional_record = some_optional_record
      self.some_record_array = some_record_array
      self.some_record_map = some_record_map
      self.some_enum_array = some_enum_array
      self.payload_key = payload_key
    end

    # @override
    def schema
      'MySchemaWithComplexTypes'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      payload = {
        'test_id' => @test_id,
        'test_float' => @test_float,
        'test_array' => @test_array,
        'some_record' => @some_record&.to_h,
        'some_optional_record' => @some_optional_record&.to_h,
        'some_record_array' => @some_record_array.map { |v| v&.to_h },
        'some_record_map' => @some_record_map.transform_values { |v| v&.to_h },
        'some_enum_array' => @some_enum_array.map { |v| v&.to_h }
      }
      @payload_key.present? ? payload.merge('payload_key' => @payload_key) : payload
    end
  end
end
