# frozen_string_literal: true

# This file is autogenerated by Deimos, Do NOT modify
module Deimos
  # :nodoc:
  class MySchema < SchemaClass::Record
    # Attribute Accessors
    # @param value [String]
    attr_accessor :test_id
    # @param value [Integer]
    attr_accessor :some_int
    # @return [Object] An optional payload key
    attr_accessor :payload_key

    # @override
    def initialize(test_id: nil,
                   some_int: nil,
                   payload_key: nil)
      super()
      self.test_id = test_id
      self.some_int = some_int
      self.payload_key = payload_key
    end

    # @override
    def schema
      'MySchema'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      payload = {
        'test_id' => @test_id,
        'some_int' => @some_int
      }
      @payload_key.present? ? payload.merge('payload_key' => @payload_key) : payload
    end
  end
end
