# frozen_string_literal: true

# autogenerated by Deimos, do not modify
module Deimos
  # :nodoc:
  class MySchema < SchemaRecord
    ### Attribute Readers ###
    # @return [String]
    attr_reader :test_id
    # @return [Integer]
    attr_reader :some_int

    # @return [Object] An optional payload key
    attr_accessor :payload_key

    ### Attribute Setters ###
    # @param value [String]
    def test_id=(value)
      @test_id = value
    end

    # @param value [Integer]
    def some_int=(value)
      @some_int = value
    end

    # @override
    def initialize(test_id:, some_int:, payload_key: nil)
      super()
      self.test_id = test_id
      self.some_int = some_int
      self.payload_key = payload_key
    end

    # @override
    def schema
      'MySchema'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      payload = {
        'test_id' => @test_id,
        'some_int' => @some_int
      }
      @payload_key.present? ? payload.merge('payload_key' => @payload_key) : payload
    end
  end
end
