# frozen_string_literal: true

# autogenerated by Deimos, do not modify
module Deimos
  # :nodoc:
  class MySchemaKey < SchemaRecord
    # @return [String]
    attr_accessor :test_id

    # @override
    def initialize(test_id:, payload_key:nil)
      @test_id = test_id
    end

    # @override
    def self.initialize_from_payload(payload)
      return unless payload.present?

      args = {}
      payload.each do |key, value|
        args[key.to_sym] = value
      end
      self.new(**args)
    end

    # @override
    def schema
      'MySchema-key'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      {
        'test_id' => @test_id
      }
    end
  end
end
