# frozen_string_literal: true

# This file is autogenerated by Deimos, Modify at your own risk
module Deimos
  # :nodoc:
  class MySchemaKey < SchemaRecord

    # @param value [String]
    attr_accessor :test_id

    # @override
    def initialize(test_id:)
      super()
      self.test_id = test_id
    end

    # @override
    def schema
      'MySchema-key'
    end

    # @override
    def namespace
      'com.my-namespace'
    end

    # @override
    def to_h
      {
        'test_id' => @test_id
      }
    end
  end
end
